"""feat: login -> email, -surname

Revision ID: 6cd711aaab44
Revises: 90402d2449eb
Create Date: 2025-11-23 21:21:30.269822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd711aaab44'
down_revision: Union[str, Sequence[str], None] = '90402d2449eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'login')
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
