"""Добавлено ограничение по длине строки

Revision ID: 8a8bec6e99d6
Revises: 6cd711aaab44
Create Date: 2025-12-02 19:59:45.258053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8bec6e99d6'
down_revision: Union[str, Sequence[str], None] = '6cd711aaab44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
