"""core: users

Revision ID: be8a4cb1f458
Revises: 
Create Date: 2025-11-20 10:41:09.940732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8a4cb1f458'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpu')
    op.drop_table('groups')
    op.drop_table('gpu_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpu_groups',
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('gpu_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu.id'], name=op.f('gpu_groups_gpu_id_fkey')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('gpu_groups_group_id_fkey')),
    sa.PrimaryKeyConstraint('group_id', 'gpu_id', name=op.f('gpu_groups_pkey'))
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('groups_pkey')),
    sa.UniqueConstraint('name', name=op.f('groups_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('gpu',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('gpu_pkey'))
    )
    # ### end Alembic commands ###
